version: '3.1'

services:

  db:
    build: ./db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./databases:/var/lib/mysql
    ports:
      - 3306:3306

#  adminer:
#    build: ./adminer
#    restart: always
#    ports:
#      - 6080:8080

#  express:
#    build: ./
#    restart: always
#    ports:
#      - 3000:3000
